# Generated by Django 4.0.4 on 2022-05-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='description',
            new_name='text',
        ),
    ]
